/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionType = IDL.Variant({
  'mcq' : IDL.Null,
  'shortAnswer' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  'round' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Participant = IDL.Record({
  'name' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'registeredAt' : IDL.Int,
  'college' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'registrationNumber' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
});
export const Answer = IDL.Record({
  'answer' : IDL.Text,
  'questionId' : IDL.Nat,
});
export const Submission = IDL.Record({
  'answers' : IDL.Vec(Answer),
  'submittedAt' : IDL.Int,
  'score' : IDL.Int,
  'participant' : Participant,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([Question], [], []),
  'addWhitelistedEmail' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getAllParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllWhitelistedEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExportData' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int)
        ),
      ],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getParticipant' : IDL.Func([IDL.Text], [Participant], ['query']),
  'getParticipantResults' : IDL.Func([IDL.Text], [Submission], ['query']),
  'getQuestionsByRound' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuizResultsDetailed' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'answers' : IDL.Vec(Answer),
          'score' : IDL.Int,
          'questions' : IDL.Vec(Question),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailWhitelisted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerParticipant' : IDL.Func([Participant], [], []),
  'removeWhitelistedEmail' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuiz' : IDL.Func([IDL.Text, IDL.Vec(Answer), IDL.Int], [], []),
  'updateQuestion' : IDL.Func([IDL.Nat, Question], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionType = IDL.Variant({
    'mcq' : IDL.Null,
    'shortAnswer' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
    'round' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Participant = IDL.Record({
    'name' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'registeredAt' : IDL.Int,
    'college' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'registrationNumber' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
  });
  const Answer = IDL.Record({ 'answer' : IDL.Text, 'questionId' : IDL.Nat });
  const Submission = IDL.Record({
    'answers' : IDL.Vec(Answer),
    'submittedAt' : IDL.Int,
    'score' : IDL.Int,
    'participant' : Participant,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([Question], [], []),
    'addWhitelistedEmail' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getAllParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllWhitelistedEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExportData' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int)
          ),
        ],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getParticipant' : IDL.Func([IDL.Text], [Participant], ['query']),
    'getParticipantResults' : IDL.Func([IDL.Text], [Submission], ['query']),
    'getQuestionsByRound' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuizResultsDetailed' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'answers' : IDL.Vec(Answer),
            'score' : IDL.Int,
            'questions' : IDL.Vec(Question),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailWhitelisted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerParticipant' : IDL.Func([Participant], [], []),
    'removeWhitelistedEmail' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuiz' : IDL.Func([IDL.Text, IDL.Vec(Answer), IDL.Int], [], []),
    'updateQuestion' : IDL.Func([IDL.Nat, Question], [], []),
  });
};

export const init = ({ IDL }) => { return []; };