/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'answer' : string, 'questionId' : bigint }
export interface Participant {
  'name' : string,
  'registrationNumber' : string,
  'email' : string,
  'registeredAt' : bigint,
  'college' : string,
}
export interface Question {
  'id' : bigint,
  'subject' : string,
  'text' : string,
  'correctAnswer' : string,
  'questionType' : QuestionType,
  'options' : [] | [Array<string>],
  'round' : bigint,
}
export type QuestionType = { 'mcq' : null } |
  { 'shortAnswer' : null };
export interface Submission {
  'answers' : Array<Answer>,
  'submittedAt' : bigint,
  'score' : bigint,
  'participant' : Participant,
}
export interface UserProfile {
  'name' : string,
  'registrationNumber' : [] | [string],
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[Question], undefined>,
  'addWhitelistedEmail' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getAllParticipants' : ActorMethod<[], Array<Participant>>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllWhitelistedEmails' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExportData' : ActorMethod<
    [],
    Array<[string, string, string, string, bigint, bigint]>
  >,
  'getLeaderboard' : ActorMethod<[], Array<Submission>>,
  'getParticipant' : ActorMethod<[string], Participant>,
  'getParticipantResults' : ActorMethod<[string], Submission>,
  'getQuestionsByRound' : ActorMethod<[bigint], Array<Question>>,
  'getQuestionsBySubject' : ActorMethod<[string], Array<Question>>,
  'getQuizResultsDetailed' : ActorMethod<
    [string],
    {
      'answers' : Array<Answer>,
      'score' : bigint,
      'questions' : Array<Question>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailWhitelisted' : ActorMethod<[string], boolean>,
  'registerParticipant' : ActorMethod<[Participant], undefined>,
  'removeWhitelistedEmail' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuiz' : ActorMethod<[string, Array<Answer>, bigint], undefined>,
  'updateQuestion' : ActorMethod<[bigint, Question], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];